// Auto-generated by the Cloudflare Worker deploy job.
// Do not edit manually — changes will be overwritten on next deploy.
const CONFIG = {
  workerUrl: "https://cv-tailor.marcos-account-aa6.workers.dev",
};
